# Generated by Django 6.1 on 2026-08-25 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals_metadata', '0013_trackchanges'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField()),
                ('bpod_file_path', models.CharField(help_text='Path to the source .mesc file.', max_length=500)),
                ('training_unit_range', models.CharField(help_text='Example: 10:21,25:55', max_length=200)),
                ('notes', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_sessions', to='animals_metadata.animal')),
            ],
            options={
                'verbose_name': 'Training Session',
                'verbose_name_plural': 'Training Sessions',
                'ordering': ['-training_date'],
            },
        ),
    ]
