# Generated by Django 6.1 on 2026-08-26 14:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0020_alter_historicalviralinjection_virus_id_and_more'),
        ('training_metadata', '0002_trackchanges_historicaltrainingsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackchanges',
            name='category',
            field=models.CharField(choices=[('training_session', 'Training Session'), ('mouse_body_weight', 'Mouse Body Weight Record')], max_length=30),
        ),
        migrations.CreateModel(
            name='HistoricalMouseBodyWeightRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('body_weight_g', models.FloatField(verbose_name='Body Weight in Grams')),
                ('percent_body_weight', models.FloatField(blank=True, null=True, verbose_name='% Body Weight Compared to Start')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('animal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='animals_metadata.animal', verbose_name='Mouse ID')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Mouse Body Weight Record',
                'verbose_name_plural': 'historical Mice Body Weight Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MouseBodyWeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('body_weight_g', models.FloatField(verbose_name='Body Weight in Grams')),
                ('percent_body_weight', models.FloatField(blank=True, null=True, verbose_name='% Body Weight Compared to Start')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body_weight_records', to='animals_metadata.animal', verbose_name='Mouse ID')),
            ],
            options={
                'verbose_name': 'Mouse Body Weight Record',
                'verbose_name_plural': 'Mice Body Weight Records',
                'ordering': ['-date', 'animal'],
            },
        ),
    ]
