# Generated by Django 6.1 on 2026-08-27 08:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def migrate_records_to_entries(apps, schema_editor):
    MouseBodyWeightRecord = apps.get_model('training_metadata', 'MouseBodyWeightRecord')
    MouseBodyWeight = apps.get_model('training_metadata', 'MouseBodyWeight')
    BodyWeightEntry = apps.get_model('training_metadata', 'BodyWeightEntry')

    for record in MouseBodyWeightRecord.objects.all():
        tracker, _ = MouseBodyWeight.objects.get_or_create(animal_id=record.animal_id)
        BodyWeightEntry.objects.create(
            tracker=tracker,
            date=record.date,
            body_weight_g=record.body_weight_g,
            percent_body_weight=record.percent_body_weight,
            notes=record.notes,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0020_alter_historicalviralinjection_virus_id_and_more'),
        ('training_metadata', '0003_alter_trackchanges_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMouseBodyWeight',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('animal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='animals_metadata.animal', verbose_name='Animal ID')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Mouse Body Weight Record',
                'verbose_name_plural': 'historical Mice Body Weight Records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MouseBodyWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='body_weight_tracker', to='animals_metadata.animal', verbose_name='Animal ID')),
            ],
            options={
                'verbose_name': 'Mouse Body Weight Record',
                'verbose_name_plural': 'Mice Body Weight Records',
                'ordering': ['animal__animal_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBodyWeightEntry',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('body_weight_g', models.FloatField(verbose_name='Body Weight in Grams')),
                ('percent_body_weight', models.FloatField(blank=True, null=True, verbose_name='% Body Weight Compared to Start')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tracker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training_metadata.mousebodyweight', verbose_name='Mouse Body Weight')),
            ],
            options={
                'verbose_name': 'historical Body Weight Entry',
                'verbose_name_plural': 'historical Body Weight Entries',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='BodyWeightEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('body_weight_g', models.FloatField(verbose_name='Body Weight in Grams')),
                ('percent_body_weight', models.FloatField(blank=True, null=True, verbose_name='% Body Weight Compared to Start')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='training_metadata.mousebodyweight', verbose_name='Mouse Body Weight')),
            ],
            options={
                'verbose_name': 'Body Weight Entry',
                'verbose_name_plural': 'Body Weight Entries',
                'ordering': ['date'],
            },
        ),
        migrations.RunPython(migrate_records_to_entries, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='HistoricalMouseBodyWeightRecord',
        ),
        migrations.DeleteModel(
            name='MouseBodyWeightRecord',
        ),
    ]
