# Generated by Django 6.1 on 2026-09-01 15:29

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_metadata', '0004_remove_mousebodyweightrecord_animal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message recorded if training analysis fails.'),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='metrics_json',
            field=models.JSONField(blank=True, default=dict, help_text='Calculated integrals and session summary metrics.'),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='output_excel_path',
            field=models.CharField(blank=True, help_text='Path to the exported Excel licking traces file.', max_length=500),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='output_log_path',
            field=models.CharField(blank=True, help_text='Path to pipeline log if available.', max_length=500),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='output_plot_path',
            field=models.CharField(blank=True, help_text='Path to the generated average lick traces plot PNG.', max_length=500),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='output_raster_path',
            field=models.CharField(blank=True, help_text='Path to the generated lick occurrences raster plot PNG.', max_length=500),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaltrainingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message recorded if training analysis fails.'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='metrics_json',
            field=models.JSONField(blank=True, default=dict, help_text='Calculated integrals and session summary metrics.'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='output_excel_path',
            field=models.CharField(blank=True, help_text='Path to the exported Excel licking traces file.', max_length=500),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='output_log_path',
            field=models.CharField(blank=True, help_text='Path to pipeline log if available.', max_length=500),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='output_plot_path',
            field=models.CharField(blank=True, help_text='Path to the generated average lick traces plot PNG.', max_length=500),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='output_raster_path',
            field=models.CharField(blank=True, help_text='Path to the generated lick occurrences raster plot PNG.', max_length=500),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bodyweightentry',
            name='body_weight_g',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01, message='Body weight must be greater than 0.')], verbose_name='Body Weight in Grams'),
        ),
        migrations.AlterField(
            model_name='historicalbodyweightentry',
            name='body_weight_g',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.01, message='Body weight must be greater than 0.')], verbose_name='Body Weight in Grams'),
        ),
        migrations.AlterField(
            model_name='historicaltrainingsession',
            name='bpod_file_path',
            field=models.CharField(help_text='Path to the source BPod .mat file.', max_length=500),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='bpod_file_path',
            field=models.CharField(help_text='Path to the source BPod .mat file.', max_length=500),
        ),
    ]
