# Generated by Django 6.1 on 2026-09-03 14:44

import imaging_metadata.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_metadata', '0005_historicaltrainingsession_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltrainingsession',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details recorded if the analysis job fails.'),
        ),
        migrations.AlterField(
            model_name='historicaltrainingsession',
            name='training_unit_range',
            field=models.CharField(help_text='Example: 10:21,25:55', max_length=200, validators=[imaging_metadata.validators.validate_measurement_unit_ranges]),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details recorded if the analysis job fails.'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='training_unit_range',
            field=models.CharField(help_text='Example: 10:21,25:55', max_length=200, validators=[imaging_metadata.validators.validate_measurement_unit_ranges]),
        ),
    ]
