# Generated by Django 6.1 on 2026-08-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imaging_metadata', '0004_remove_imagingsession_number_of_planes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('imaging_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_runs', to='imaging_metadata.imagingsession')),
            ],
            options={
                'verbose_name': 'Analysis Run',
                'verbose_name_plural': 'Analysis Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
