# Generated by Django 6.1 on 2026-08-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='frame_rate',
            field=models.FloatField(blank=True, help_text='Frame rate detected by the imaging analysis pipeline (Hz).', null=True),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='number_of_planes',
            field=models.PositiveIntegerField(blank=True, help_text='Number of imaging planes detected by the imaging analysis pipeline.', null=True),
        ),
    ]
