# Generated by Django 6.1 on 2026-08-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0002_analysisrun_frame_rate_analysisrun_number_of_planes'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='suite2p_git_commit',
            field=models.CharField(blank=True, help_text='Git commit hash of the customized Suite2p code used for this run.', max_length=64),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='suite2p_version',
            field=models.CharField(blank=True, help_text='Suite2p version used for this analysis run.', max_length=100),
        ),
    ]
