# Generated by Django 6.1 on 2026-08-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0003_analysisrun_suite2p_git_commit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='parameter_log_path',
            field=models.CharField(blank=True, help_text='Path to the Suite2p parameter log generated for this analysis run.', max_length=500),
        ),
    ]
