# Generated by Django 6.1 on 2026-08-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0004_analysisrun_parameter_log_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrun',
            name='number_of_planes',
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='default_diameter',
            field=models.FloatField(default=12.0, help_text='Expected cell diameter used for Suite2p cell detection.'),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='tau',
            field=models.FloatField(default=0.7, help_text='Calcium indicator decay time constant used for analysis.'),
        ),
    ]
