# Generated by Django 6.1 on 2026-08-14 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0005_remove_analysisrun_number_of_planes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='default_diameter',
            field=models.FloatField(default=12.0, help_text='Expected cell diameter used for Suite2p cell detection.', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='tau',
            field=models.FloatField(default=0.7, help_text='Calcium indicator decay time constant used for analysis.', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
