# Generated by Django 6.1 on 2026-08-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0006_alter_analysisrun_default_diameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message recorded if the analysis run fails.'),
        ),
    ]
