# Generated by Django 6.1 on 2026-08-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0007_analysisrun_error_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrun',
            name='suite2p_git_commit',
        ),
        migrations.RemoveField(
            model_name='analysisrun',
            name='suite2p_version',
        ),
    ]
