# Generated by Django 6.1 on 2026-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0008_remove_analysisrun_suite2p_git_commit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='frame_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Frame rate detected by the imaging analysis pipeline (Hz).', max_digits=8, null=True),
        ),
    ]
