# Generated by Django 6.1 on 2026-08-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0009_alter_analysisrun_frame_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrun',
            name='default_diameter',
        ),
        migrations.RemoveField(
            model_name='analysisrun',
            name='tau',
        ),
    ]
