# Generated by Django 6.1 on 2026-08-15 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0010_remove_analysisrun_default_diameter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisrun',
            old_name='parameter_log_path',
            new_name='output_resource_path',
        ),
    ]
