# Generated by Django 6.1 on 2026-08-15 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0011_rename_parameter_log_path_analysisrun_output_resource_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisrun',
            name='output_resource_path',
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='default_diameter',
            field=models.FloatField(default=12.0, help_text='Expected cell diameter used for Suite2p cell detection.', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='output_log_path',
            field=models.CharField(blank=True, help_text='Path to the pipeline log generated for this analysis run.', max_length=500),
        ),
        migrations.AddField(
            model_name='analysisrun',
            name='tau',
            field=models.FloatField(default=0.7, help_text='Calcium indicator decay time constant used for analysis.', validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='output_path',
            field=models.CharField(blank=True, help_text='Base directory containing Suite2p analysis outputs.', max_length=500),
        ),
    ]
