# Generated by Django 6.1 on 2026-08-26 10:55

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0012_remove_analysisrun_output_resource_path_and_more'),
        ('imaging_metadata', '0005_alter_imagingsession_measurement_unit_ranges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('analysis_run', 'Analysis Run')], max_length=30)),
                ('animal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(choices=[('+', 'Created'), ('~', 'Updated'), ('-', 'Deleted')], max_length=1)),
                ('changed_at', models.DateTimeField()),
                ('changed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Track Change',
                'verbose_name_plural': 'Track Changes',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAnalysisRun',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('frame_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Frame rate detected by the imaging analysis pipeline (Hz).', max_digits=8, null=True)),
                ('default_diameter', models.FloatField(default=12.0, help_text='Expected cell diameter used for Suite2p cell detection.', validators=[django.core.validators.MinValueValidator(0.01)])),
                ('tau', models.FloatField(default=0.7, help_text='Calcium indicator decay time constant used for analysis.', validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output_log_path', models.CharField(blank=True, help_text='Path to the pipeline log generated for this analysis run.', max_length=500)),
                ('output_path', models.CharField(blank=True, help_text='Base directory containing Suite2p analysis outputs.', max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message recorded if the analysis run fails.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('imaging_session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='imaging_metadata.imagingsession')),
            ],
            options={
                'verbose_name': 'historical Analysis Run',
                'verbose_name_plural': 'historical Analysis Runs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
