# Generated by Django 6.1 on 2026-09-03 14:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_analysis_metadata', '0013_trackchanges_historicalanalysisrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='analysisrun',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details recorded if the analysis job fails.'),
        ),
        migrations.AlterField(
            model_name='historicalanalysisrun',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalanalysisrun',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details recorded if the analysis job fails.'),
        ),
    ]
