# Generated by Django 6.1 on 2026-08-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_identifier', models.CharField(help_text='Animal or subject identifier used for this imaging session.', max_length=100)),
                ('acquisition_date', models.DateField()),
                ('imaging_region', models.CharField(blank=True, max_length=100, null=True)),
                ('mesc_file_path', models.CharField(help_text='Path to the source .mesc file.', max_length=500)),
                ('measurement_unit_ranges', models.CharField(help_text='Example: 10:21,25:55', max_length=200)),
                ('number_of_planes', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Imaging Session',
                'verbose_name_plural': 'Imaging Sessions',
                'ordering': ['-acquisition_date'],
            },
        ),
    ]
