# Generated by Django 6.1 on 2026-08-14 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0013_trackchanges'),
        ('imaging_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingsession',
            name='animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imaging_sessions', to='animals_metadata.animal'),
        ),
        migrations.AlterField(
            model_name='imagingsession',
            name='animal_identifier',
            field=models.CharField(help_text='Temporary field retained while migrating existing imaging sessions.', max_length=100),
        ),
    ]
