# Generated by Django 6.1 on 2026-08-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0013_trackchanges'),
        ('imaging_metadata', '0002_imagingsession_animal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagingsession',
            name='animal_identifier',
        ),
        migrations.AlterField(
            model_name='imagingsession',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_sessions', to='animals_metadata.animal'),
        ),
    ]
