# Generated by Django 6.1 on 2026-08-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_metadata', '0003_remove_imagingsession_animal_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagingsession',
            name='number_of_planes',
        ),
    ]
