# Generated by Django 6.1 on 2026-08-14 12:46

import imaging_metadata.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imaging_metadata', '0004_remove_imagingsession_number_of_planes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingsession',
            name='measurement_unit_ranges',
            field=models.CharField(help_text='Example: 10:21,25:55', max_length=200, validators=[imaging_metadata.validators.validate_measurement_unit_ranges]),
        ),
    ]
