# Generated by Django 6.1 on 2026-08-26 10:55

import django.db.models.deletion
import imaging_metadata.validators
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0019_remove_historicalviralinjection_injection_site_and_more'),
        ('imaging_metadata', '0005_alter_imagingsession_measurement_unit_ranges'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('imaging_session', 'Imaging Session')], max_length=30)),
                ('animal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(choices=[('+', 'Created'), ('~', 'Updated'), ('-', 'Deleted')], max_length=1)),
                ('changed_at', models.DateTimeField()),
                ('changed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Track Change',
                'verbose_name_plural': 'Track Changes',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalImagingSession',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('acquisition_date', models.DateField()),
                ('imaging_region', models.CharField(blank=True, max_length=100, null=True)),
                ('mesc_file_path', models.CharField(help_text='Path to the source .mesc file.', max_length=500)),
                ('measurement_unit_ranges', models.CharField(help_text='Example: 10:21,25:55', max_length=200, validators=[imaging_metadata.validators.validate_measurement_unit_ranges])),
                ('notes', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('animal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='animals_metadata.animal')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Imaging Session',
                'verbose_name_plural': 'historical Imaging Sessions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
