# Generated by Django 6.1 on 2026-08-26 12:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('virus', 'Virus')], max_length=30)),
                ('animal_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Virus ID')),
                ('action', models.CharField(choices=[('+', 'Created'), ('~', 'Updated'), ('-', 'Deleted')], max_length=1)),
                ('changed_at', models.DateTimeField()),
                ('changed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Track Change',
                'verbose_name_plural': 'Track Changes',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virus_id', models.CharField(max_length=100, unique=True, verbose_name='Virus ID')),
                ('viral_construct', models.CharField(max_length=255, verbose_name='Viral Construct')),
                ('titre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre')),
                ('location_in_fridge', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location in -80°C Fridge')),
                ('virus_owner', models.CharField(blank=True, choices=[('AC', 'Abhrajyoti'), ('TB', 'Balázs'), ('VK', 'Varada')], max_length=100, null=True, verbose_name='Virus Owner')),
            ],
            options={
                'verbose_name': 'Virus',
                'verbose_name_plural': 'Viruses',
                'ordering': ['virus_id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVirus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('virus_id', models.CharField(db_index=True, max_length=100, verbose_name='Virus ID')),
                ('viral_construct', models.CharField(max_length=255, verbose_name='Viral Construct')),
                ('titre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titre')),
                ('location_in_fridge', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location in -80°C Fridge')),
                ('virus_owner', models.CharField(blank=True, choices=[('AC', 'Abhrajyoti'), ('TB', 'Balázs'), ('VK', 'Varada')], max_length=100, null=True, verbose_name='Virus Owner')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Virus',
                'verbose_name_plural': 'historical Viruses',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
