# Generated by Django 6.1 on 2026-08-07 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=10, unique=True)),
                ('genotype', models.CharField(choices=[('Thy1-Cre', 'Thy1-Cre'), ('Thy1-gcamp6s', 'Thy1/gcamp6s (Tg)')], max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('cage_id', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animals',
            },
        ),
        migrations.CreateModel(
            name='VisionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_test_result', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail')], max_length=10)),
                ('vision_test_type', models.CharField(choices=[('SweepTest', 'Vision Sweep Test'), ('qOMR', 'qOMR')], max_length=10)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_metadata.animal')),
            ],
            options={
                'verbose_name': 'Vision Check',
                'verbose_name_plural': 'Vision Check',
            },
        ),
    ]
