# Generated by Django 6.1 on 2026-08-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='owner',
            field=models.CharField(blank=True, choices=[('AC', 'Abhrajyoti'), ('TB', 'Balázs')], max_length=100, null=True),
        ),
    ]
