# Generated by Django 6.1 on 2026-08-07 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0002_animal_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViralInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virus_name', models.CharField(choices=[('AAV322', 'AAV322'), ('AAV418', 'AAV418')], max_length=100)),
                ('virus_construct', models.CharField(choices=[('AAV9-hSyn-DIO-jGCaMP8s-P2A-ChrimsonR-ST', 'AAV9-hSyn-DIO-jGCaMP8s-P2A-ChrimsonR-ST')], max_length=100)),
                ('injection_date', models.DateField()),
                ('injection_site', models.CharField(choices=[('V1', 'V1')], max_length=100)),
                ('volume_ul', models.FloatField(verbose_name='Volume (µL)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_metadata.animal')),
            ],
            options={
                'verbose_name': 'Viral Injections',
                'verbose_name_plural': 'Viral Injections',
            },
        ),
    ]
