# Generated by Django 6.1 on 2026-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0003_viralinjection'),
    ]

    operations = [
        migrations.AddField(
            model_name='viralinjection',
            name='expression_pattern',
            field=models.TextField(blank=True, null=True),
        ),
    ]
