# Generated by Django 6.1 on 2026-08-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0004_viralinjection_expression_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='visioncheck',
            name='data_path',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='viralinjection',
            name='volume_ul',
            field=models.FloatField(verbose_name='Volume (nL)'),
        ),
    ]
