# Generated by Django 6.1 on 2026-08-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0005_visioncheck_data_path_alter_viralinjection_volume_ul'),
    ]

    operations = [
        migrations.AddField(
            model_name='viralinjection',
            name='injection_person',
            field=models.CharField(blank=True, choices=[('AC', 'Abhrajyoti'), ('TB', 'Balázs'), ('VK', 'Varada')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='owner',
            field=models.CharField(blank=True, choices=[('AC', 'Abhrajyoti'), ('TB', 'Balázs'), ('VK', 'Varada')], max_length=100, null=True),
        ),
    ]
