# Generated by Django 6.1 on 2026-08-07 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0006_viralinjection_injection_person_alter_animal_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viralinjection',
            old_name='injection_person',
            new_name='injecting_person',
        ),
    ]
