# Generated by Django 6.1 on 2026-08-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0007_rename_injection_person_viralinjection_injecting_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='status',
            field=models.CharField(blank=True, choices=[('Alive', 'Alive'), ('Dead', 'Dead')], max_length=100, null=True),
        ),
    ]
