# Generated by Django 6.1 on 2026-08-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0008_animal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='ogr_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
