# Generated by Django 6.1 on 2026-08-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0009_animal_ogr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
