# Generated by Django 6.1 on 2026-08-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0010_animal_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='viralinjection',
            name='surgery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='surgery_person',
            field=models.CharField(blank=True, choices=[('AC', 'Abhrajyoti'), ('TB', 'Balázs'), ('VK', 'Varada')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cage_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
