# Generated by Django 6.1 on 2026-08-08 14:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0011_viralinjection_surgery_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAnimal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('animal_id', models.CharField(db_index=True, max_length=10)),
                ('owner', models.CharField(blank=True, choices=[('AC', 'Abhrajyoti'), ('TB', 'Balázs'), ('VK', 'Varada')], max_length=100, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('genotype', models.CharField(choices=[('Thy1-Cre', 'Thy1-Cre'), ('Thy1-gcamp6s', 'Thy1/gcamp6s (Tg)')], max_length=100)),
                ('cage_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ogr_id', models.CharField(blank=True, max_length=100, null=True)),
                ('project_id', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('status', models.CharField(blank=True, choices=[('Alive', 'Alive'), ('Dead', 'Dead')], max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Animal',
                'verbose_name_plural': 'historical Animals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalViralInjection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('virus_name', models.CharField(choices=[('AAV322', 'AAV322'), ('AAV418', 'AAV418')], max_length=100)),
                ('virus_construct', models.CharField(choices=[('AAV9-hSyn-DIO-jGCaMP8s-P2A-ChrimsonR-ST', 'AAV9-hSyn-DIO-jGCaMP8s-P2A-ChrimsonR-ST')], max_length=100)),
                ('injection_date', models.DateField()),
                ('injecting_person', models.CharField(blank=True, choices=[('AC', 'Abhrajyoti'), ('TB', 'Balázs'), ('VK', 'Varada')], max_length=100, null=True)),
                ('injection_site', models.CharField(choices=[('V1', 'V1')], max_length=100)),
                ('volume_ul', models.FloatField(verbose_name='Volume (nL)')),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('surgery_person', models.CharField(blank=True, choices=[('AC', 'Abhrajyoti'), ('TB', 'Balázs'), ('VK', 'Varada')], max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('expression_pattern', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('animal_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='animals_metadata.animal')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Viral Injections',
                'verbose_name_plural': 'historical Viral Injections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalVisionCheck',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('vision_test_type', models.CharField(choices=[('SweepTest', 'Vision Sweep Test'), ('qOMR', 'qOMR')], max_length=10)),
                ('vision_test_result', models.CharField(choices=[('P', 'Pass'), ('F', 'Fail')], max_length=10)),
                ('data_path', models.CharField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('animal_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='animals_metadata.animal')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Vision Check',
                'verbose_name_plural': 'historical Vision Check',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
