# Generated by Django 6.1 on 2026-08-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0012_historicalanimal_historicalviralinjection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackChanges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('animal', 'Animal'), ('vision_check', 'Vision Check'), ('viral_injection', 'Viral Injection')], max_length=30)),
                ('animal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(choices=[('+', 'Created'), ('~', 'Updated'), ('-', 'Deleted')], max_length=1)),
                ('changed_at', models.DateTimeField()),
                ('changed_by', models.CharField(blank=True, max_length=150, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Track Change',
                'verbose_name_plural': 'Track Changes',
                'ordering': ['-changed_at'],
            },
        ),
    ]
