# Generated by Django 6.1 on 2026-08-25 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0013_trackchanges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalviralinjection',
            name='virus_construct',
        ),
        migrations.RemoveField(
            model_name='viralinjection',
            name='virus_construct',
        ),
    ]
