# Generated by Django 6.1 on 2026-08-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0014_remove_historicalviralinjection_virus_construct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalviralinjection',
            old_name='virus_name',
            new_name='virus_id',
        ),
        migrations.RenameField(
            model_name='viralinjection',
            old_name='virus_name',
            new_name='virus_id',
        ),
    ]
