# Generated by Django 6.1 on 2026-08-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0015_rename_virus_name_historicalviralinjection_virus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalviralinjection',
            name='injection_date',
            field=models.DateField(verbose_name='Inj. Date'),
        ),
        migrations.AlterField(
            model_name='historicalviralinjection',
            name='injection_site',
            field=models.CharField(choices=[('V1', 'V1')], max_length=100, verbose_name='Inj. Site'),
        ),
        migrations.AlterField(
            model_name='viralinjection',
            name='injection_date',
            field=models.DateField(verbose_name='Inj. Date'),
        ),
        migrations.AlterField(
            model_name='viralinjection',
            name='injection_site',
            field=models.CharField(choices=[('V1', 'V1')], max_length=100, verbose_name='Inj. Site'),
        ),
    ]
