# Generated by Django 6.1 on 2026-08-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0016_alter_historicalviralinjection_injection_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalviralinjection',
            name='expression_pattern',
        ),
        migrations.RemoveField(
            model_name='viralinjection',
            name='expression_pattern',
        ),
        migrations.AddField(
            model_name='historicalviralinjection',
            name='expression',
            field=models.TextField(blank=True, null=True, verbose_name='Expression (Checkup MESc file)'),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='expression',
            field=models.TextField(blank=True, null=True, verbose_name='Expression (Checkup MESc file)'),
        ),
    ]
