# Generated by Django 6.1 on 2026-08-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0017_remove_historicalviralinjection_expression_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalviralinjection',
            name='virus_id_2',
            field=models.CharField(blank=True, choices=[('AAV322', 'AAV322'), ('AAV418', 'AAV418')], max_length=100, null=True, verbose_name='Virus ID 2'),
        ),
        migrations.AddField(
            model_name='historicalviralinjection',
            name='virus_id_3',
            field=models.CharField(blank=True, choices=[('AAV322', 'AAV322'), ('AAV418', 'AAV418')], max_length=100, null=True, verbose_name='Virus ID 3'),
        ),
        migrations.AddField(
            model_name='historicalviralinjection',
            name='volume_nl_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume 2 (nL)'),
        ),
        migrations.AddField(
            model_name='historicalviralinjection',
            name='volume_nl_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume 3 (nL)'),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='virus_id_2',
            field=models.CharField(blank=True, choices=[('AAV322', 'AAV322'), ('AAV418', 'AAV418')], max_length=100, null=True, verbose_name='Virus ID 2'),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='virus_id_3',
            field=models.CharField(blank=True, choices=[('AAV322', 'AAV322'), ('AAV418', 'AAV418')], max_length=100, null=True, verbose_name='Virus ID 3'),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='volume_nl_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume 2 (nL)'),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='volume_nl_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume 3 (nL)'),
        ),
        migrations.AlterField(
            model_name='historicalviralinjection',
            name='virus_id',
            field=models.CharField(choices=[('AAV322', 'AAV322'), ('AAV418', 'AAV418')], max_length=100, verbose_name='Virus ID 1'),
        ),
        migrations.AlterField(
            model_name='historicalviralinjection',
            name='volume_ul',
            field=models.FloatField(verbose_name='Volume 1 (nL)'),
        ),
        migrations.AlterField(
            model_name='viralinjection',
            name='virus_id',
            field=models.CharField(choices=[('AAV322', 'AAV322'), ('AAV418', 'AAV418')], max_length=100, verbose_name='Virus ID 1'),
        ),
        migrations.AlterField(
            model_name='viralinjection',
            name='volume_ul',
            field=models.FloatField(verbose_name='Volume 1 (nL)'),
        ),
    ]
