# Generated by Django 6.1 on 2026-08-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0018_historicalviralinjection_virus_id_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalviralinjection',
            name='injection_site',
        ),
        migrations.RemoveField(
            model_name='viralinjection',
            name='injection_site',
        ),
        migrations.AddField(
            model_name='historicalviralinjection',
            name='depth',
            field=models.FloatField(blank=True, null=True, verbose_name='Depth 1 (μm)'),
        ),
        migrations.AddField(
            model_name='historicalviralinjection',
            name='depth_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Depth 2 (μm)'),
        ),
        migrations.AddField(
            model_name='historicalviralinjection',
            name='depth_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Depth 3 (μm)'),
        ),
        migrations.AddField(
            model_name='historicalviralinjection',
            name='site',
            field=models.CharField(blank=True, choices=[('V1', 'V1')], max_length=100, null=True, verbose_name='Injection Site 1'),
        ),
        migrations.AddField(
            model_name='historicalviralinjection',
            name='site_2',
            field=models.CharField(blank=True, choices=[('V1', 'V1')], max_length=100, null=True, verbose_name='Injection Site 2'),
        ),
        migrations.AddField(
            model_name='historicalviralinjection',
            name='site_3',
            field=models.CharField(blank=True, choices=[('V1', 'V1')], max_length=100, null=True, verbose_name='Injection Site 3'),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='depth',
            field=models.FloatField(blank=True, null=True, verbose_name='Depth 1 (μm)'),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='depth_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Depth 2 (μm)'),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='depth_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Depth 3 (μm)'),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='site',
            field=models.CharField(blank=True, choices=[('V1', 'V1')], max_length=100, null=True, verbose_name='Injection Site 1'),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='site_2',
            field=models.CharField(blank=True, choices=[('V1', 'V1')], max_length=100, null=True, verbose_name='Injection Site 2'),
        ),
        migrations.AddField(
            model_name='viralinjection',
            name='site_3',
            field=models.CharField(blank=True, choices=[('V1', 'V1')], max_length=100, null=True, verbose_name='Injection Site 3'),
        ),
    ]
