# Generated by Django 6.1 on 2026-08-26 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0019_remove_historicalviralinjection_injection_site_and_more'),
        ('virus_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalviralinjection',
            name='virus_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='virus_metadata.virus', to_field='virus_id', verbose_name='Virus ID 1'),
        ),
        migrations.AlterField(
            model_name='historicalviralinjection',
            name='virus_id_2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='virus_metadata.virus', to_field='virus_id', verbose_name='Virus ID 2'),
        ),
        migrations.AlterField(
            model_name='historicalviralinjection',
            name='virus_id_3',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='virus_metadata.virus', to_field='virus_id', verbose_name='Virus ID 3'),
        ),
        migrations.AlterField(
            model_name='viralinjection',
            name='virus_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viral_injections_1', to='virus_metadata.virus', to_field='virus_id', verbose_name='Virus ID 1'),
        ),
        migrations.AlterField(
            model_name='viralinjection',
            name='virus_id_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viral_injections_2', to='virus_metadata.virus', to_field='virus_id', verbose_name='Virus ID 2'),
        ),
        migrations.AlterField(
            model_name='viralinjection',
            name='virus_id_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viral_injections_3', to='virus_metadata.virus', to_field='virus_id', verbose_name='Virus ID 3'),
        ),
    ]
