# Generated by Django 6.1 on 2026-09-03 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0020_alter_historicalviralinjection_virus_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='Animal ID'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='cage_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cage ID'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='ogr_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OGR ID'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='historicalanimal',
            name='animal_id',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Animal ID'),
        ),
        migrations.AlterField(
            model_name='historicalanimal',
            name='cage_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cage ID'),
        ),
        migrations.AlterField(
            model_name='historicalanimal',
            name='ogr_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OGR ID'),
        ),
        migrations.AlterField(
            model_name='historicalanimal',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project ID'),
        ),
        migrations.AlterField(
            model_name='historicalvisioncheck',
            name='animal_id',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='animals_metadata.animal', verbose_name='Animal ID'),
        ),
        migrations.AlterField(
            model_name='visioncheck',
            name='animal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animals_metadata.animal', verbose_name='Animal ID'),
        ),
    ]
