# Generated by Django 6.1 on 2026-09-03 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_metadata', '0021_alter_animal_animal_id_alter_animal_cage_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalvisioncheck',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Vision Check', 'verbose_name_plural': 'historical Vision Checks'},
        ),
        migrations.AlterModelOptions(
            name='visioncheck',
            options={'verbose_name': 'Vision Check', 'verbose_name_plural': 'Vision Checks'},
        ),
        migrations.AlterField(
            model_name='viralinjection',
            name='animal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals_metadata.animal'),
        ),
        migrations.AlterField(
            model_name='visioncheck',
            name='animal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals_metadata.animal', verbose_name='Animal ID'),
        ),
    ]
